-   hosts: target
    remote_user: root
    vars:
        file_list:
            ## file which need to be unpacked, the key need to be the directory name. So you need unpack it first and see what it exactly be.
            neo:
                name: neo.tar.gz
                is_url: 'no'
                src_path: neo.tar.gz
                dst_path: /usr/local/neo
                need_unpack: 'yes'
                need_clear: 'no'
            ##    with_notify: 'no'
            pip.conf:
                name: pip.conf
                is_url: 'no'
                src_path: /etc/pip.conf
                dst_path: /usr/local/pip.conf
                need_unpack: 'no'
                need_clear: 'no'
            ##    with_notify: 'no'
    roles:
        - {role: file_push, "{{file_list}}"}
