#########留一个疑问, 为什么default下面的变量不能被common本身的task获取到???
## 安装包资源路径
RES_IP: 172.16.3.102
RES_PREFIX: /ops/deployment_res/ew4/service
res_path: /ops/deployment_res/ew4/service/edge
edge: /ops/deployment_res/ew4/service/edge
chat: "{{RES_PREFIX}}"/chat
login: "{{RES_PREFIX}}"/login
logic: "{{RES_PREFIX}}"/logic

## pip包的默认后缀
suffix: .zip

## 下载安装包的暂存路径
tmpPath: /tmp

## 目标工程路径
PRO_PATH:
  edge: /opt/ew4-edge-server
  chat: /opt/ew4-chat-server
  login: /opt/ew4-login-server
  logic: /opt/ew4-logic-server